### ISSUE TITLE
startup error with last update

### ISSUE THREAD

**Issue by mahfuj2507** [trgkanki/ankitime#28]
![image](https://user-images.githubusercontent.com/117604264/211207998-a43a1fe3-785b-4aa9-afe5-ab520814d7e2.png)

Worked fine before the update

Anki Version - Windows 10 home
Version ⁨2.1.54 (b6a7760c)⁩
Python 3.9.7 Qt 6.3.1 PyQt 6.3.1

**Comment by phu54321** [comment]
Could you check the latest update?

Possibly related to updated packager: https://github.com/trgkanki/trgkanki-template-cli/blob/77b51972733d9027a5f98cd0c28027fd9c68ce28/package.json#L37

**Comment by mahfuj2507** [comment]
> Could you check the latest update?
> 
> Possibly related to updated packager: https://github.com/trgkanki/trgkanki-template-cli/blob/77b51972733d9027a5f98cd0c28027fd9c68ce28/package.json#L37

Yea the latest update fixed it, thanks for the quick fix. i really like this add-on :D
