### ISSUE TITLE
ambient sound during the review

### ISSUE THREAD

**Issue by igormeduff** [trgkanki/ankitime#32]
# Feature request

## Problem description

> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## Suggested solution

> A clear and concise description of what you want to happen.

## Alternative solutions you've thought of\

> A clear and concise description of any alternative solutions or features you've considered.

## Additional context

> Add any other context or screenshots about the feature request here.

**Comment by igormeduff** [comment]
It would be perfect if you could add ambient sound during the review and other ambient sound to the menu. It would look similar to a game like that. I'm not a programmer, so I don't know how difficult it is to create this.

**Comment by phu54321** [comment]
Overcomplicate things. Just put your favorite music player on the background while reviewing.
